services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    depends_on:
      - db
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    #   SPRING_DATASOURCE_USERNAME: postgres
    #   SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    # networks:
    #   - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
